using Content.Shared.Actions;

namespace Content.Server._Crescent.Psionics;

public abstract partial class HardbloodArtsTargetEvent : EntityTargetActionEvent
{

    /// <summary>
    ///     How much blood this power requires to use.
    /// </summary>
    [DataField]
    public float BloodUsage = 1f;

    /// <summary>
    ///     Whether this power checks if the wearer is psionically insulated.
    /// </summary>
    [DataField]
    public bool CheckInsulation;

    /// <summary>
    ///     Whether this power generates glimmer when used.
    /// </summary>
    [DataField]
    public bool DoGlimmerEffects;

    /// <summary>
    ///     The minimum amount of glimmer generated by this power.
    /// </summary>
    [DataField]
    public int MinGlimmer;

    /// <summary>
    ///     The maximum amount of glimmer generated by this power.
    /// </summary>
    [DataField]
    public int MaxGlimmer;

    /// <summary>
    ///    The name of the power, for logging purposes.
    /// </summary>
    [DataField]
    public string PowerName;
}
